#pragma once

#include "model/coordinate.hpp"

namespace tengen::engine {

//! What the engine decided to do on its turn.
enum class MoveAction { Place,
	                    Pass,
	                    Resign };

//! A move generated by the engine.
struct BotMove {
	MoveAction action{MoveAction::Pass}; //!< Type of the generated move.
	tengen::Coord coord{};               //!< Board position. Only meaningful for MoveAction::Place.
};

} // namespace tengen::engine
